# Generated by Django 4.0.4 on 2022-05-01 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='class_number',
            name='class_description',
            field=models.TextField(default='description..', max_length=250),
        ),
    ]
