# Generated by Django 4.0.4 on 2022-05-01 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_class_number_class_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='class_number',
            name='class_chairs',
            field=models.IntegerField(default=20),
        ),
    ]
